apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-lndjuykj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-lndjuykj 
  name: go-lndjuykj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-lndjuykj
    weight: 100 
